<script src="<?=$this->basePath() . '/' . $this->requireJsUrl?>"></script>
<script src="<?=$this->basePath(). '/' . $this->configUrl?>"></script>
<script>
    requirejs.config({
        baseUrl: '<?=$this->basePath()?>/',
        config: <?= json_encode((object)$this->config) ?>,
        paths: <?= json_encode((object)$this->paths) ?>
    });
</script>
<?php if ($this->buildConfigUrl):?>
    <script src="<?=$this->buildConfigUrl?>"></script>
<?php endif?>
<script>require(<?= json_encode($this->loadModules) ?>);</script>